# @package _global_

defaults:
  - _self_
  - datamodule: default.yaml
  - model: automodel.yaml
  - task: mrpc.yaml
  - callbacks: null
  - logger: tensorboard.yaml
  - trainer: default.yaml
  - experiment: null
  - hydra: default.yaml

# path to original working directory
work_dir: ${hydra:runtime.cwd}

model_name: bert-base-uncased
do_train: True
do_eval: True
cache_dir: ${work_dir}/cache
seed: 42

exp_name: ${model_name}/${task.task_name}