# @package _global_

defaults:
  - _self_
  - datamodule: default.yaml
  - model: automodel.yaml
  - task: mrpc.yaml
  - callbacks: null
  - logger: null
  - trainer: default.yaml
  - log_dir: null
  - experiment: null
  - debug: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# path to original working directory
original_work_dir: ${hydra:runtime.cwd}

# disable python warnings if they annoy you
ignore_warnings: True

name: "default"

model_name: bert-base-uncased
do_train: True
do_eval: True
cache_dir: ${original_work_dir}/tmp
output_dir: ${original_work_dir}/tmp/${datamodule.task_name}
seed: 42